Update Kibana dashboards and Elastic configuration
ergon/airlock-minikube-example pull request #15
Opened 2021-03-24 11:36 UTC by orltom

2021-03-24 12:16 UTC, orltom commented on data/elasticsearch/airlock-waf-template.json
> -		"airlock-logs-*"
FYI: I have noticed that the new template remove the airlock-logs pattern.

2021-03-24 12:16 UTC, orltom commented on .github/test/cypress.json
> +  "baseUrl": "https://host.docker.internal/"
Without the trailing slash the Kibana test will fail

2021-03-25 06:20 UTC, dieti80 requested changes
The changed files look fine to me. Anyway, discover and dashboards does not work anymore and must be fixed.

2021-03-25 12:21 UTC, dieti80 commented on .github/test/cypress.json
> +  "baseUrl": "https://host.docker.internal/"
There shouldn't be any rewrites required. Kibana is configured with the ENV variables to run under /kibana.
See kibana.yaml
The required ENV variables are: SERVER_BASEPATH and SERVER_REWRITEBASEPATH

2021-03-25 12:21 UTC, dieti80 commented on data/elasticsearch/airlock-waf-template.json
> -		"airlock-logs-*"
Everything looks fine in Kibana. Guess this was never required.

2021-03-25 12:22 UTC, dieti80 approved these changes

2021-03-25 13:34 UTC, merged